# run boot/stage/4/make/mix.sh
# run boot/stage/4/sed/mix.sh
# run boot/stage/4/gawk/mix.sh
# run boot/stage/4/grep/mix.sh
# run boot/stage/4/coreutils/mix.sh
# run boot/stage/5/dash/mix.sh
# run boot/stage/5/diffutils/mix.sh
# run boot/stage/5/findutils/mix.sh
# run boot/stage/6/pkg-config/mix.sh
# run env/bootstrap/mix.sh
