# run boot/stage/4/make/package.sh
# run boot/stage/4/sed/package.sh
# run boot/stage/4/gawk/package.sh
# run boot/stage/4/grep/package.sh
# run boot/stage/4/coreutils/package.sh
# run boot/stage/5/dash/package.sh
# run boot/stage/5/diffutils/package.sh
# run boot/stage/5/findutils/package.sh
# run boot/stage/2/shutil/package.py
# run env/bootstrap/package.py
