#!/usr/bin/env sh

set -xue

curl 'https://repology.org/api/v1/projects/?maintainer=anton%40samokhvalov.xyz&outdated=1' | ./flt | while read l; do
    echo ${l}

    if ./up ${l}; then
        git add -A
        git commit -m "up"
    else
        git checkout .
    fi
done
