#!/usr/bin/env python3

import sys

sys.setrecursionlimit(10000)
sys.dont_write_bytecode = True

import os

me = os.path.normpath(os.path.abspath(__file__))

sys.path.append(os.path.dirname(me))

for x in ('jinja-3.1.2/src', 'markupsafe-2.1.1/src'):
    sys.path.append(os.path.join(os.path.dirname(me), 'deps', x))

if __name__ == '__main__':
    import core.entry as ce
    ce.entry(me)
