#!/usr/bin/env python3

import sys
sys.dont_write_bytecode = True

import traceback
sys.excepthook = traceback.print_exception

import ssl
ssl._create_default_https_context = ssl._create_unverified_context

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

import os
os.environ['SSL_CERT_FILE'] = 'nowhere'

import signal

def on_sigint(*args):
    os._exit(1)

signal.signal(signal.SIGINT, on_sigint)

import core.main as cm


if __name__ == '__main__':
    sys.exit(cm.main(sys.argv, os.path.normpath(os.path.abspath(__file__))))
