#!/usr/bin/env python3

import os
import sys
import json
import time
import subprocess

GOOD = frozenset('0123456789abcdef')
sent = '1' * 64

def call1(*cmd):
    return subprocess.check_output(list(cmd), stdin=None)

def call(*cmd):
    try:
        return subprocess.check_output(list(cmd), stdin=None, stderr=subprocess.STDOUT)
    except Exception as e:
        return e.stdout

def run(*cmd):
    return subprocess.check_call(list(cmd), stdin=None)

def is_sha(x):
    x = x.removeprefix('sha:')

    if len(x) != 64:
        return False

    for ch in x:
        if ch not in GOOD:
            return False

    return True

def parse_sha(data):
    for l in data.split('\n'):
        for x in l.split(' '):
            if is_sha(x):
                return x.removeprefix('sha:')

    raise Exception('no sha')

def subst_sha(data, to):
    return data.replace(parse_sha(data), to)

def fix1(pn, fr, to):
    with open(pn) as f:
        data = f.read()

    if fr not in data:
        return

    nd = subst_sha(data, sent).replace(fr, to)

    if nd:
        with open(pn, 'w') as f:
            f.write(nd)

def fix2(pn, sha):
    with open(pn) as f:
        data = f.read()

    nd = data.replace(sent, sha)

    with open(pn, 'w') as f:
        f.write(nd)

def it_recs(pkg, fr):
    with open('pkgs/die/scripts/dump.json') as f:
        for l in f.read().split('\n'):
            if fr not in l:
                continue

            rec = json.loads(l)

            if rec['pkg_name'].startswith(pkg):
                yield rec

def it_pkgs(recs):
    for c in recs:
        yield c['ix_pkg_full_name']

def it_files(pkgs):
    for p in pkgs:
        for x in call1('./ix', 'dep', p).decode().split('\n'):
            if x.strip():
                yield x.strip()

def revstr(s):
    return ''.join(reversed(s))

def process(pkg, fr, to):
    recs = list(it_recs(pkg, fr))
    pkgs = list(it_pkgs(recs))

    if not pkgs:
        print(f'nothing to do')

        return

    run('./ix', 'build', *pkgs)

    files = list(sorted(frozenset(it_files(pkgs))))

    for f in files:
        print(f'prepare {f}')
        fix1('pkgs/' + f, fr, to)

    run('git', 'diff')

    out = call('./ix', 'build', *pkgs).decode()
    sha = revstr(parse_sha(revstr(out.replace(sent, '').replace('sha:', ''))))

    for f in files:
        print(f'fix {f}')
        fix2('pkgs/' + f, sha)

    run('git', 'diff')
    run('./ix', 'build', *pkgs)

try:
    process(sys.argv[1], sys.argv[2], sys.argv[3])
except Exception as e:
    print('revert all')
    run('git', 'checkout', '.')
    raise e
