#!/usr/bin/env sh

set -xue

chro "${3}"
tar --sort=name --owner=root:0 --group=root:0 --mtime='UTC 1970-01-01'  -c -f "${2}.tmp" "${3}"
lz4 "${2}.tmp" "${2}"
sha256sum "${2}"
echo "${1}  ${2}" | sha256sum -cw
