{% extends '//lib/mu/pdf/t/ix.sh' %}

{% block make_flags %}
{{super()}}
HAVE_GLUT=no
{% endblock %}

{% block c_rename_symbol %}
{{super()}}
_cmsReadHeader
_cmsSearchTag
_cmsWriteHeader
cmsCloseIOhandler
cmsCreateProfilePlaceholder
cmsGetHeaderCreator
cmsGetHeaderFlags
cmsGetHeaderManufacturer
cmsGetHeaderRenderingIntent
cmsGetProfileIOhandler
cmsGetTagCount
cmsGetTagSignature
cmsIsTag
cmsOpenIOhandlerFromFile
cmsOpenIOhandlerFromMem
cmsOpenIOhandlerFromNULL
cmsOpenIOhandlerFromStream
cmsSetHeaderFlags
cmsSetHeaderManufacturer
cmsSetHeaderRenderingIntent
_cmsGetTagTrueType
cmsCloseProfile
cmsGetColorSpace
cmsGetDeviceClass
cmsGetEncodedICCversion
cmsGetHeaderAttributes
cmsGetHeaderCreationDateTime
cmsGetHeaderModel
cmsGetHeaderProfileID
cmsGetPCS
cmsGetProfileVersion
cmsLinkTag
cmsOpenProfileFromFile
cmsOpenProfileFromMem
cmsOpenProfileFromStream
cmsReadRawTag
cmsReadTag
cmsSaveProfileToFile
cmsSaveProfileToIOhandler
cmsSaveProfileToMem
cmsSaveProfileToStream
cmsSetColorSpace
cmsSetDeviceClass
cmsSetEncodedICCversion
cmsSetHeaderAttributes
cmsSetHeaderModel
cmsSetHeaderProfileID
cmsSetPCS
cmsSetProfileVersion
cmsTagLinkedTo
cmsWriteRawTag
cmsWriteTag
{% endblock %}
