#!/usr/bin/env sh

echo '------------------------------------------------------'
set -xue
date
sleep 50
git pull
IX_ROOT=~/ix_root IX_EXEC_KIND=local ./ix build set/ci bld/all
./ix mut ci set/ci bld/all
