#!/usr/bin/env python3

import os

VER = '''
{% block git_version %}
v3
{% endblock %}
'''

def fix(d, p):
    return d.replace(VER, '').strip() + '\n'

for a, b, c in os.walk('.'):
    for x in c:
        if '.sh' in x:
            p = os.path.join(a, x)

            with open(p, 'r') as f:
                d = f.read()

            try:
                dd = fix(d, p)
            except Exception as e:
                print(f'skip {p}, {e}, {repr(e)}')
                dd = None

            if dd and d != dd:
                print(f'fix {p}')

                with open(p, 'w') as f:
                    f.write(dd)
