#!/usr/bin/env python3

import os
import sys
import json
import itertools

import urllib.request as ur


def iter_recs(args):
    for a in args:
        url = f'https://pypi.python.org/pypi/{a}/json'
        data = json.loads(ur.urlopen(url).read())

        for rec in data['urls']:
            if '.whl' in rec['url']:
                yield f'{a}/ix.sh', {
                    'url': rec['url'],
                    'md5': rec['md5_digest'],
                }


def dict_merge(it):
    res = {}

    for k, v in it:
        res[k] = dict(itertools.chain(res.get(k, {}).items(), v.items()))

    return res


def main():
    cur = json.loads(sys.stdin.read())
    pkg = sys.argv[1:]

    if not pkg:
        pkg = [os.path.dirname(x) for x in cur]

    print(json.dumps(dict_merge(itertools.chain(cur.items(), iter_recs(pkg))), indent=4, sort_keys=True))

main()
