#!/usr/bin/env sh

set -ue

cd $(dirname ${IX_BINARY})/pkgs/die/scripts/

(
cat urls.txt
IX_DUMP_GRAPH=1 "${IX_BINARY}" build set/ci | grep -v GOPROXY | grep '"http' | sed -e 's|.*"http|http|' | sed -e 's|".*||'
find ${IX_PKGS_ROOT} -name 'ix.sh' | xargs cat | grep "https://"
find ${IX_PKGS_ROOT} -name 'ix.sh' | xargs cat | grep "http://"
) | grep -v '#' \
  | grep -v ' ' \
  | grep -v '{{' \
  | grep -v 'ix-eparo-mirror.duckdns.org' \
  | sort | uniq > _
mv _ urls.txt
