#!/usr/bin/env sh

set -ue

cd $(dirname ${IX_BINARY})/pkgs/die/scripts/

export LANG=C
export LC_ALL=C

(
cat urls.txt
IX_DUMP_GRAPH=1 "${IX_BINARY}" build set/ci 2>/dev/null | sed -e 's|\"|\n|g' | grep -v GOPROXY | grep '"http' | sed -e 's|.*"http|http|' | sed -e 's|".*||'
find ${IX_PKGS_ROOT} -name '*.sh' | xargs cat | grep "http[s]*://"
) | grep -v '#'  \
  | grep -v ' '  \
  | grep -v '{{' \
  | grep -v 'ix-eparo-mirror.duckdns.org' \
  | grep -v 'ix.kmeaw.com' \
  | grep -v 'ix-mirror.mooo.com' \
  | grep -v 'ix.vvzvlad.xyz' \
  | grep -v 'ix.7mind.io' \
  | sort -s | uniq > _
mv _ urls.txt
