# run gnu/file/mix.sh
# run gnu/findutils/mix.sh
# run gnu/sed/mix.sh
# run gnu/gawk/mix.sh
# run gnu/grep/mix.sh
# run gnu/patch/mix.sh
# run gnu/diffutils/mix.sh
# run gnu/coreutils/8.31/mix.sh
# run shell/cli/dash/minimal/mix.sh
