#pragma once

#define ABSL_OPTION_USE_STD_ANY 1
#define ABSL_OPTION_USE_STD_OPTIONAL 1
#define ABSL_OPTION_USE_STD_STRING_VIEW 1
#define ABSL_OPTION_USE_STD_VARIANT 1
#define ABSL_OPTION_USE_STD_SOURCE_LOCATION 2
#define ABSL_OPTION_USE_STD_ORDERING 0
#define ABSL_OPTION_USE_INLINE_NAMESPACE 1
#define ABSL_OPTION_INLINE_NAMESPACE_NAME lts_20260817
#define ABSL_OPTION_HARDENED 0
#define ABSL_OPTION_INLINE_HW_ACCEL_STRATEGY 0
#define ABSL_FORCE_WAITER_MODE 4
