#!/usr/bin/env sh

out="${1}"

mkdir -p ${out}/lib ${out}/include ${out}/bin

find . -type f -name '*.h' | while read l; do
    cp ${l} ${out}/include/
done

find . -type f -name '*.a' | while read l; do
    cp ${l} ${out}/lib/
done

find . -type f -executable | while read l; do
    cp ${l} ${out}/bin/
done
